### ISSUE TITLE
Add Steps in README.md

### ISSUE THREAD

**Issue by alisolanki** [alisolanki/Welcome-to-Open-Source#14]
If you can solve this issue, write it in the comments and I'll assign this issue to you.

Add steps to adding yourself to the contributors list in README.md file. The steps would include installing Git installation, forking, git clone command to get the repository, etc.

You can go through the video to write down the steps.

**Comment by rootxrishabh** [comment]
Hello, @alisolanki I would like to work on this, can you please assign this to me?

**Comment by rootxrishabh** [comment]
@alisolanki just to be sure, steps have to be written onto a separate file eg "CONTRIBUTING.md" or added to the README.md file itself?

**Comment by alisolanki** [comment]
Yes, in a separate CONTRIBUTING.md file.

And update the README.md file with a step to read CONTRIBUTING.md file before making a PR
