### ISSUE TITLE
Adding a Table Row after every 7 contributors

### ISSUE THREAD

**Issue by alisolanki** [alisolanki/Welcome-to-Open-Source#20]
Anyone who can take up this issue can comment down below

Add a new Table Row (<tr></tr>) after every 7 contributors in a row.

<img width="890" alt="Screenshot 2023-03-16 at 6 18 35 PM" src="https://user-images.githubusercontent.com/55312000/225621847-3e59ac9d-732b-4afe-ac56-3258ac5df2fe.png">

The last contributor should be in a new row.

**Comment by lmutum** [comment]
added

**Comment by Saksham093** [comment]
Great work for new borns to open source ... But for this, I want to contribute by fixing this issue and also enhance the look wise.

Would you assign me this ?

**Comment by priyanshu-11000** [comment]
Yeah, this is a good first issue for beginners like me;)
So would you like to assign it to me?

**Comment by Saksham093** [comment]
> Great work for new borns to open source ... But for this, I want to contribute by fixing this issue and also enhance the look wise.
> 
> Would you assign me this ?

![](https://user-images.githubusercontent.com/69385787/225784288-97af5a88-6d8b-47cd-bc7f-20a48f1ba034.png)

This is my work.

**Comment by alisolanki** [comment]
Perfect @Saksham093

**Comment by alisolanki** [comment]
Please make a Pull Request for it @Saksham093

**Comment by Saksham093** [comment]
Thank you but it is already done.

![](https://user-images.githubusercontent.com/69385787/225949292-612a7cbf-e561-4e10-bbe9-dff370a9e2e1.png)

I hope, I don't have to add PR. but Thank You for assigning me

**Comment by BejadiRajeshReddy18** [comment]
Assign it to me

**Comment by theNKCode** [comment]
Added table row after 7th contributer.
