### ISSUE TITLE
Need contributors to manage the repository

### ISSUE THREAD

**Issue by alisolanki** [alisolanki/Welcome-to-Open-Source#90]
Currently there are a lot of Pull Requests coming in!!!

If someone has experience with managing Github Repositories can comment down below and I'll promote them to manage the repository.

PS. Only comment if you have prior experience with managing repositories.

**Comment by Saksham093** [comment]
Ya, I would help you to manage these PRs but let me know the rules for when to merge.

Note: I will monitor once or twice a day.

**Comment by alisolanki** [comment]
@Saksham093 Merge needs to be done if they have followed the steps correctly and added their data in <td></td>

Usually this would give a merge conflict, and would need to be resolved manually.

**Comment by Saksham093** [comment]
Okay.... @alisolanki I will do this work.

**Comment by shubham-singh-748** [comment]
it seems looks interesting to me, i would love to work on, if no one is working.....

**Comment by byomkesh03** [comment]
I would love to do this...

**Comment by Muhammad-Awab** [comment]
Yes I can do this.

**Comment by moudekarvivek** [comment]
Yes,Sure

**Comment by MKisKrazy** [comment]
i will help too

**Comment by alisolanki** [comment]
I'm checking past contributions and activity on Github as a basis of selection. Comment if you have been active on Github and I'll add you to manage the repo.

**Comment by alisolanki** [comment]
What needs to be done?
- Check if contributors are **adding** their name, many people are just changing the existing contributor's names and adding their instead (ask them to resubmit PR if they've not done so)
- As people are adding their names to the same file, we need to resolve conflicts before merge and they would
(shown in video)

https://user-images.githubusercontent.com/55312000/227008650-7a6e68b1-aa83-4263-83d7-685824826c17.mov

**Comment by Muhammad-Awab** [comment]
I am active on GitHub. Check My previous contributions.

**Comment by MKisKrazy** [comment]
should we also check if they are adding their name at end of the code or ?

**Comment by alisolanki** [comment]
This was a bad idea😶
